import boto3

def create_cmk(alias, desc='Customer Master Key'):
    """Create a KMS Customer Master Key

    The created CMK is a Customer-managed key stored in AWS KMS.

    :param desc: key description
    :return Tuple(KeyId, KeyArn) where:
        KeyId: AWS globally-unique string ID
        KeyArn: Amazon Resource Name of the CMK
    :return Tuple(None, None) if error
    """

    # Create CMK
    kms_client = boto3.client('kms')
    try:
        response = kms_client.create_key(Description=desc)
        
    except ClientError as e:
        logging.error(e)
        return None, None

    # Return the key ID and ARN
    return response['KeyMetadata']['KeyId'], response['KeyMetadata']['Arn']


def create_alias(keyId, alias):
    """Create an Alias
    """

    kms_client = boto3.client('kms')
    try:
        response = kms_client.create_alias(
            # The alias to create. Aliases must begin with 'alias/'. Do not use aliases that begin with 'alias/aws' because they are reserved for use by AWS.
            AliasName=alias,
            # The identifier of the CMK whose alias you are creating. You can use the key ID or the Amazon Resource Name (ARN) of the CMK.
            TargetKeyId=keyId,
        )
    except ClientError as e:
        logging.error(e)
        return None, None
    return response



response = create_cmk('This key was generated by rgomis')
print(response)
response = create_alias(response[0], 'alias/my-rgomis-kms-key')
print(response)